### ISSUE TITLE
endpoint方法无法接收传入的headers

### ISSUE THREAD

**Issue by JokerChat** [we-lsp/atomic-bomb-engine-py#1]
**示例代码**
`import atomic_bomb_engine
import asyncio

async def run_batch():
    print("开始压测")
    headers = {"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MDU2Mzg1NSIsImNsaWVudFR5cGUiOiJwYyIsImFwcFR5cGUiOiJwb3J0YWwiLCJleHAiOjE3MTAzNTQ5MDgsImlhdCI6MTcxMDMxMTAwOH0.PYsbF5vVL_DVlkOHcyN27fupHX_tVuGhkNDBjRsH-EQ"}
    data = {"timeType":4,"times":[],"pageNum":1,"pageSize":10}
    result = await atomic_bomb_engine.batch_async(test_duration_secs=10, concurrent_requests=50, api_endpoints=[
               atomic_bomb_engine.endpoint(
                   name="抖音素材列表接口",
                   url="http://mallapi.bluemoon.com.cn/ec-oms/ebp-live/admin/material/tiktok/list",
                   method="POST",
                   weight=1,
                   timeout_secs=5,
                   headers = headers,
                   json = data,
                   assert_options=[atomic_bomb_engine.assert_option(jsonpath="$.responseCode", reference_object=200)]
               )
           ])
    print(result)

async def listen():
  iterator = atomic_bomb_engine.BatchListenIter()
  for message in iterator:
      if message:
          print(message)
      else:
          await asyncio.sleep(0.3)

async def main():
  await asyncio.gather(
      run_batch(),
      listen(),
  )

if __name__ == "__main__":
  asyncio.run(main())`
  通过Charles抓包发现实际没有传入headers
![image](https://github.com/qyzhg/atomic-bomb-engine-py/assets/47030789/6cc5f6be-f657-4f95-8a09-6756cf4eb2ac)
**预期结果**
endpoint方法可以接收传入的headers

**Comment by qyzhg** [comment]
引擎代码构建完请求头后，忘记添加到request中

![image](https://github.com/qyzhg/atomic-bomb-engine-py/assets/55947523/8330c048-3631-4bbe-b7ff-fddb16ef438f)

修复引擎后，包装器版本号+1

**Comment by qyzhg** [comment]
0.3.8版本python包已修复
包名改为atomic-bomb-engine防止引起混淆
pip install atomic-bomb-engine==0.3.8更新可解决该问题
