### ISSUE TITLE
有一个问题想请教一下作者，我想通过atomic-bomb-engine引擎结合ws实现一个压测功能，发现首次连接ws的时候执行压测没有问题，消息也会正常推送，但是后续重新连接并执行时压测程序会正常执行，listen_batch这个监听方法似乎有些问题，我在里面加了一个调试，直接发送消息是没问题的，不太确定是不是BatchListenIter这个迭代器的实现问题？尝试了很多方式，还是没能找到问题，想请作者帮忙看看。（如果作者觉得跟本库无关，也可以忽略我这个问题）

### ISSUE THREAD

**Issue by InnSea** [we-lsp/atomic-bomb-engine-py#147]
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/130050263/d092d5dc-f720-4e9c-8622-f9ffdca4e843)

**Comment by InnSea** [comment]
这是首次连接：
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/130050263/e8dfb7f2-f4a1-4dc5-ac73-56800d1fdaad)

这是非首次连接：
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/130050263/0a700564-ea59-4cb8-94cb-f38d57dedb64)

**Comment by qyzhg** [comment]
我猜是我这边的问题，我这边只用了一个通道，在一次压测完成后会将这个通道关闭，后续我规划下修改一下这个问题，现在如果做平台的话，需要将这个iter重新实例化，我感觉让每次任务用进程隔离应该是没问题的

**Comment by InnSea** [comment]
好的，感谢作者回复！

**Comment by InnSea** [comment]
如果后续规划支持解决了这个问题，烦请作者issue里踢我一下，感谢！ 🤗

**Comment by qyzhg** [comment]
争取下周解决

**Comment by InnSea** [comment]
对了，针对这个问题能否提一个需求，就是可不可以增加一个类似于stop的方法来终止和销毁程序呢？

**Comment by qyzhg** [comment]
单独开一个issue吧

**Comment by qyzhg** [comment]
这次的改动非常的大
在任务运行的时候将使用stream返回数据
为了解决gil问题，使用rust做了个独立的python异步runtime
先发布一个rc版本你试一下
看你是自己做平台，python的那个ui装饰器我先没做适配
你这边实验成功了之后，合并到正式release再关闭
```shell
pip install atomic_bomb_engine==0.39.0-rc.1
```
使用这个命令安装rc版
```python
import asyncio
import time

import atomic_bomb_engine


async def main():
    runner = atomic_bomb_engine.BatchRunner()
    runner.run(
        test_duration_secs=300,
        concurrent_requests=30,
        step_option=atomic_bomb_engine.step_option(increase_step=3, increase_interval=3),
        timeout_secs=15,
        cookie_store_enable=True,
        verbose=False,
        api_endpoints=[
            atomic_bomb_engine.endpoint(
                name="test-1",
                url="http://127.0.0.1:8000/",
                method="get",
                weight=100,
                assert_options=[
                    atomic_bomb_engine.assert_option(jsonpath="$.msg", reference_object="操作成功"),
                ],
            ),
        ])
    return runner


if __name__ == '__main__':
    results = asyncio.run(main())
    for res in results:
        if res.get("should_wait"):
            time.sleep(0.1)
        print(res)
```

这样使用

大概解释一下
runner = atomic_bomb_engine.BatchRunner()
实例化这个类，会初始化一个异步运行时和一个流式通道
调用run后，会执行压测，并且将数据生产到流式通道中（全是异步）
这个runner实现了python生成器协议
可以使用next()或者直接循环迭代
返回值是一个dict
如果在这个dict中存在should_wait这个值，表示流处理器还没有准备好，可以等待一下再继续

**Comment by InnSea** [comment]
好，我先试试看

**Comment by qyzhg** [comment]
好，你先试一下，可以的话给我个回复，我适配前端发布正式版
可以微信扫码进群，沟通方便些

**Comment by qyzhg** [comment]
https://github.com/we-lsp/atomic-bomb-engine-py/commit/8133aac00c874af5056f0702ade8e8dc6384ef24
done
