### ISSUE TITLE
为啥这个初始化过程如此漫长

### ISSUE THREAD

**Issue by yioyoiyioys222** [we-lsp/atomic-bomb-engine-py#155]
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/50391716/a3693e37-6693-4a50-98c9-2f63bbb115bd)

还有结果返回的时候可以不返回{'should_wait': True}哇？

**Comment by qyzhg** [comment]
读取到需要等待的时候加个异步的sleep让出cpu试试，不加的话cpu容易打满
