### ISSUE TITLE
单接口压测时，折线图中汇总曲线和对应接口曲线应该要一致。

### ISSUE THREAD

**Issue by shxxhs** [we-lsp/atomic-bomb-engine-py#62]
在做单接口压测时，折线图中汇总曲线和对应接口曲线应该要一致。
![39c67eb276fc5ddb62c480ec5e93ad9](https://github.com/qyzhg/atomic-bomb-engine-py/assets/53425838/1f67e3d2-f668-4586-a7ed-7c569132d1a9)
看着像是单接口的曲线只用了结果值来画曲线

**Comment by qyzhg** [comment]
<img width="1536" alt="image" src="https://github.com/qyzhg/atomic-bomb-engine-py/assets/55947523/e51b200e-3e26-4b35-a8bb-e29af7fcd7dc">
@GiantAxeWhy 前端大哥查收

**Comment by qyzhg** [comment]
https://github.com/GiantAxeWhy/atomic-bomb-engine-front/commit/9a069e46374c33827e8ba142c001e800afc28b70
已修复
