### ISSUE TITLE
希望可以直接上下接口的场景串联

### ISSUE THREAD

**Issue by laodengtou** [we-lsp/atomic-bomb-engine-py#88]
比如我有一个测试计划组
包含abcd四个接口，在压测中，b接口的入参需要从a接口获取，c接口的入参需要从b接口出参获取，类似这种逻辑

**Comment by qyzhg** [comment]
被压接口只能在最后一个执行

**Comment by qyzhg** [comment]
引擎开发完成，测试通过后添加进python包装器
https://github.com/we-lsp/atomic-bomb-engine/commit/52a8fc61d0b260f7a10d91abd8739f714911e6a3

**Comment by qyzhg** [comment]
done
