### ISSUE TITLE
Docker的python alpine 镜像下好像无法安装这个包？

### ISSUE THREAD

**Issue by InnSea** [we-lsp/atomic-bomb-engine-py#92]

**Comment by InnSea** [comment]
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/130050263/bb1eade6-9739-4a50-8df2-3823809491cf)

**Comment by qyzhg** [comment]
actions中没有构建Alpine Linux的版本

**Comment by qyzhg** [comment]
刚尝试了一下，github actions并不直接支持Alpine Linux的构建，现在正在休假，稍微晚点写一个构建脚本

**Comment by InnSea** [comment]
好的，感谢回复。

**Comment by qyzhg** [comment]
0.37.1版本后增加musllinux支持
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/55947523/700c9992-a404-4fef-9c87-1dbc72d607a8)

**Comment by InnSea** [comment]
感谢感谢！
