### ISSUE TITLE
GET接口1秒并发10次汇总rps与接口详情rps统计数不匹配

### ISSUE THREAD

**Issue by sunny-xiabo** [we-lsp/atomic-bomb-engine-py#98]
条件：GET接口1秒并发10次
实际结果：
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/71371027/17cdddb8-84e2-44f1-8292-81d254cd1558)
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/71371027/b13211ce-dce7-4c5f-af9f-c9d44ee59d39)

**Comment by qyzhg** [comment]
接口过慢时会出现这个问题
问题原因是：接口计数器在请求前已经+1，但是api的详情统计是响应后push，接口过慢gap会更大
![image](https://github.com/we-lsp/atomic-bomb-engine-py/assets/55947523/a8576278-bfc9-4639-9cfc-04920a08bfb7)
可以将计数器+1的代码移动到请求后，但是并不能完全消除gap,只能将gap降低到很小

❗如果需要完全消除gap,需要在共享队列生产的时候根据当前时间点刷一下rps数据，这个放到后面再优化

**Comment by qyzhg** [comment]
https://github.com/we-lsp/atomic-bomb-engine/pull/26/files
内核已跟随该版本进行了优化，尽可能的减少了gap
